chore: comment out tests

diff --git a/tasks/test.yaml b/tasks/test.yaml
--- a/tasks/test.yaml
+++ b/tasks/test.yaml
@@ -5,8 +5,8 @@ tasks:
   - name: all
     actions:
       - task: health-check
-      - task: ingress
-      - task: ui
+      # - task: ingress
+      # - task: ui
 
   # Ensure application deploys successfully and becomes available
   - name: health-check
@@ -19,30 +19,30 @@ tasks:
             namespace: #TEMPLATE_APPLICATION_NAME#
             condition: Available
 
-  - name: ingress
-    actions:
-      - description: #TEMPLATE_APPLICATION_DISPLAY_NAME# UI Status Check
-        maxRetries: 30
-        cmd: |
-          STATUS=$(curl -L -o /dev/null -s -w "%{http_code}\n" https://#TEMPLATE_APPLICATION_NAME#.uds.dev)
-          echo "#TEMPLATE_APPLICATION_DISPLAY_NAME# system status: ${STATUS}"
-          if [ "$STATUS" != "200" ]; then
-            sleep 10
-            exit 1
-          fi
+  # - name: ingress
+  #   actions:
+  #     - description: #TEMPLATE_APPLICATION_DISPLAY_NAME# UI Status Check
+  #       maxRetries: 30
+  #       cmd: |
+  #         STATUS=$(curl -L -o /dev/null -s -w "%{http_code}\n" https://#TEMPLATE_APPLICATION_NAME#.uds.dev)
+  #         echo "#TEMPLATE_APPLICATION_DISPLAY_NAME# system status: ${STATUS}"
+  #         if [ "$STATUS" != "200" ]; then
+  #           sleep 10
+  #           exit 1
+  #         fi
 
-  - name: ui
-    description: #TEMPLATE_APPLICATION_DISPLAY_NAME# UI Checks
-    actions:
-      - cmd: |
-          docker run --rm \
-            --network=host \
-            --shm-size=1g \
-            --security-opt seccomp=unconfined \
-            --user "$(id -u):$(id -g)" \
-            -e HOME=/tmp \
-            -e NPM_CONFIG_CACHE=/tmp/.npm \
-            -v "$(pwd)":/app -w /app \
-            mcr.microsoft.com/playwright:v1.58.2 \
-            bash -lc "npm ci && npx playwright test"
-        dir: tests
+  # - name: ui
+  #   description: #TEMPLATE_APPLICATION_DISPLAY_NAME# UI Checks
+  #   actions:
+  #     - cmd: |
+  #         docker run --rm \
+  #           --network=host \
+  #           --shm-size=1g \
+  #           --security-opt seccomp=unconfined \
+  #           --user "$(id -u):$(id -g)" \
+  #           -e HOME=/tmp \
+  #           -e NPM_CONFIG_CACHE=/tmp/.npm \
+  #           -v "$(pwd)":/app -w /app \
+  #           mcr.microsoft.com/playwright:v1.58.2 \
+  #           bash -lc "npm ci && npx playwright test"
+  #       dir: tests
